---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-{{ .Values.searchServiceName }}
  labels:
    run: {{ .Chart.Name }}-{{ .Values.searchServiceName }}
  annotations:
  {{- if (eq .Values.provider "aws") }}
    external-dns.alpha.kubernetes.io/hostname: {{ .Chart.Name }}-{{ .Values.searchServiceName }}-{{ .Values.environment }}.{{ .Values.dnsZone }}
    service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
    service.beta.kubernetes.io/aws-load-balancer-type: nlb 
  {{- end }}          
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - port: 5001
      name: {{ .Chart.Name }}-{{ .Values.searchServiceName }}-{{ .Values.environment }}-http
      targetPort: 5000
      nodePort: 30001
  selector:
    run: {{ .Chart.Name }}-{{ .Values.searchServiceName }}
---  
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-{{ .Values.metadataServiceName }}
  labels:
    run: {{ .Chart.Name }}-{{ .Values.metadataServiceName }} 
  annotations:
  {{- if (eq .Values.provider "aws") }}
    external-dns.alpha.kubernetes.io/hostname: {{ .Chart.Name }}-{{ .Values.metadataServiceName }}-{{ .Values.environment }}.{{ .Values.dnsZone }}
    service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
    service.beta.kubernetes.io/aws-load-balancer-type: nlb 
  {{- end }}              
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - port: 5002
      name: {{ .Chart.Name }}-{{ .Values.metadataServiceName }}-{{ .Values.environment }}-http
      targetPort: 5000
      nodePort: 30002
  selector:
    run: {{ .Chart.Name }}-{{ .Values.metadataServiceName }}
---         
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-{{ .Values.frontEndServiceName }}
  labels:
    run: {{ .Chart.Name }}-{{ .Values.frontEndServiceName }}
  annotations:
  {{- if (eq .Values.provider "aws") }}
    external-dns.alpha.kubernetes.io/hostname: {{ .Chart.Name }}-{{ .Values.frontEndServiceName }}-{{ .Values.environment }}.{{ .Values.dnsZone }}
    service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
    service.beta.kubernetes.io/aws-load-balancer-type: nlb 
  {{- end }}       
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - port: {{ .Values.frontEndServicePort }}
      name: {{ .Chart.Name }}-{{ .Values.frontEndServiceName }}-{{ .Values.environment }}-http
      targetPort: 5000
      nodePort: 30003
  selector:
    run: {{ .Chart.Name }}-{{ .Values.frontEndServiceName }}
---            