name: metadata PR
on:
  pull_request:
    paths:
      - "metadata/**"
jobs:
  test-unit-python:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: ['3.6.x', '3.7.x']
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: make install_deps && pip3 uninstall -y amundsen-common && pip3 install ../common
        working-directory: ./metadata
      - name: Run python unit tests
        run: make test
        working-directory: ./metadata
      - name: Codecov
        uses: codecov/codecov-action@v1
        with:
          directory: ./metadata
